name: Build Tauri App

on:
  push:
    tags:
      - 'app-v*'

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04' # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - if: matrix.platform == 'windows-latest'
        run: |
          git config --global core.protectNTFS false

      - uses: actions/checkout@v4

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm' # Set this to npm, yarn or pnpm.

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: pnpm install

      - uses: tauri-apps/tauri-action@v0
        id: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
          includeUpdaterJson: false

      - name: Remove version from file names (non-Windows)
        if: matrix.platform != 'windows-latest'
        id: files_unix
        run: |
          # Remove version from file names -> _<version> and -<version> are the two patterns we need to remove.
          # Also move the files into the `files` folder (make it first)
          mkdir -p files
          for file in $(echo '${{ steps.build.outputs.artifactPaths }}' | jq -r '.[]'); do
            # Get the file name without the path
            filename=$(basename "$file")
            # Remove the version from the file name
            new_filename=$(echo "$filename" | sed -E 's/(_|-)v?[0-9]+\.[0-9]+\.[0-9]+//')

            # if it ends in `.app`, zip it up first
            if [[ "$new_filename" == *.app ]]; then
              # zip it up
              zip -r "files/${new_filename}.zip" "$file"
              # remove the original file
              rm -rf "$file"
            else
              # move the file to the `files` folder
              mv "$file" "files/$new_filename"
            fi
          done
          # one per line, print out each file in the `files` folder
          echo 'FILES<<EOF' >> $GITHUB_OUTPUT
          for file in $(ls files); do
            echo "files/$file" >> $GITHUB_OUTPUT
          done
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Remove version from file names (Windows)
        if: matrix.platform == 'windows-latest'
        id: files_win
        shell: pwsh
        run: |
          # Remove version from file names -> _<version> and -<version> are the two patterns we need to remove.
          # Also move the files into the `files` folder (make it first)
          mkdir -p files
          $files = ${{ steps.build.outputs.artifactPaths }} | ConvertFrom-Json
          foreach ($file in $files) {
            # Get the file name without the path
            $filename = [System.IO.Path]::GetFileName($file)
            # Remove the version from the file name
            $new_filename = $filename -replace '(_|-)v?[0-9]+\.[0-9]+\.[0-9]+', ''

            # if it ends in `.app`, zip it up first
            if ($new_filename.EndsWith('.app')) {
              # zip it up
              Compress-Archive -Path $file -DestinationPath "files/$new_filename.zip"
              # remove the original file
              Remove-Item $file
            } else {
              # move the file to the `files` folder
              Move-Item $file "files/$new_filename"
            }
          }
          # one per line, print out each file in the `files` folder
          Write-Output 'FILES<<EOF' >> $GITHUB_OUTPUT
          Get-ChildItem files | ForEach-Object { Write-Output "files/$($_.Name)" } >> $GITHUB_OUTPUT
          Write-Output 'EOF' >> $GITHUB_OUTPUT


      - name: Unify outputs
        id: files
        run: |
          if [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
            echo "FILES<<EOF" >> $GITHUB_OUTPUT
            echo "${{ steps.files_win.outputs.FILES }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          else
            echo "FILES<<EOF" >> $GITHUB_OUTPUT
            echo "${{ steps.files_unix.outputs.FILES }}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi

      - name: Rename Mac zip
        if: matrix.platform == 'macos-latest' && matrix.args == '--target aarch64-apple-darwin'
        run: |
          mv files/Bronify.app.zip files/Bronify_aarch64.app.zip

      - name: Rename Mac zip
        if: matrix.platform == 'macos-latest' && matrix.args == '--target x86_64-apple-darwin'
        run: |
          mv files/Bronify.app.zip files/Bronify_x86_64.app.zip

      - uses: ryand56/r2-upload-action@latest
        with:
          r2-account-id: ${{ secrets.R2_ACCOUNT_ID }}
          r2-access-key-id: ${{ secrets.R2_ACCESS_KEY_ID }}
          r2-secret-access-key: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          r2-bucket: ${{ secrets.R2_BUCKET }}
          source-dir: ${{ steps.files.outputs.FILES }}
          destination-dir: ./
